#!/bin/bash
xrandr --output HDMI2 --off
xrandr --output HDMI1 --off
xrandr --output DP1 --off
xrandr --output eDP1 --off
xrandr --output DP2 --mode 3840x2160 --primary
xrandr --output eDP1 --scale 1x1
xrandr --output eDP1 --scale 2x2
