#!/bin/bash

~/.scripts/layout-docked

killall stalonetray -9
stalonetray -c ~/.config/stalonetray/docked &

~/.scripts/audio-docked

xdotool search --class "browser-LowRes" windowkill
xdotool search --class "browser-Media" windowkill
#xdotool search --classname ".*LaptopClinic.*" windowkill
firefox -P Media --class browser-Media &>/dev/null &
firefox -P LowRes --class browser-LowRes &>/dev/null &
# google-chrome-stable --user-data-dir=/home/raef/.config/google-chrome/Media &>/dev/null &

# nmcli radio wifi off

mumble  &>/dev/null &
discord &>/dev/null &
# steam-native   &>/dev/null &
google-play-music   &>/dev/null &

mount /home/raef/Media

killall xautolock -9 
light -S 100

killall nm-applet -9
nm-applet 2>/dev/null &

killall dunst -9
dunst -mon 2 &

~/.scripts/launch-polybar docked

i3-msg workspace 2:β 
i3-msg gaps inner current set 0


