#!/bin/bash
xdotool search --class "browser-LowRes" windowkill
xdotool search --class "browser-Media" windowkill
killall -9 dockswitcher
bash -c "exec -a Dockswitcher /home/raef/.scripts/dockswitcher" &>/dev/null &
