#!/bin/bash
~/.scripts/layout-roaming
~/.scripts/launch-polybar roaming
killall nm-applet
killall blueman-applet
nm-applet 2>/dev/null &
blueman-applet 2>/dev/null &
pacmd set-default-source alsa_input.pci-0000_00_1f.3.analog-stereo
pacmd set-default-sink alsa_output.pci-0000_00_1f.3.analog-stereo
xdotool search --classname ".*LowRes.*" windowkill
xdotool search --classname ".*Media.*" windowkill
killall mumble  -9
killall Discord -9
killall steam -9

i3-msg workspace 2:β
i3-msg gaps inner current set 30

