#!/bin/bash
~/.scripts/layout-roaming
~/.scripts/launch-polybar roaming
killall nm-applet
killall blueman-applet
nm-applet 2>/dev/null &
blueman-applet 2>/dev/null &
pactl set-sink-mute 0 0
pacmd set-default-source alsa_input.pci-0000_00_1f.3.analog-stereo
pacmd set-default-sink alsa_output.pci-0000_00_1f.3.analog-stereo
xdotool search --classname ".*LowRes.*" windowkill
xdotool search --classname ".*Media.*" windowkill
xdotool search --classname ".*LaptopClinic.*" windowkill
google-chrome-stable --user-data-dir=/home/raef/.config/google-chrome/LaptopClinic &>/dev/null &
killall mumble  -9
killall Discord -9
killall steam -9
killall "Google Play Music Desktop Player" -9

nmcli radio wifi on

light -S 10


xautolock -time 15 -locker "/home/raef/.scripts/lock-xwobf" &

i3-msg workspace 2:β
i3-msg gaps inner current set 30

