#!/bin/bash

background="#2D2D2D"
backgroundalt="#444444"
text="#FFFFFF"
textalt="#B5B5B5"
primary="#FF5F00"
contrast="#0087D7"

#£BACKGROUND
#£BACKGROUND-ALT
#
#£TEXT
#£TEXT-ALT
#
#£PRIMARY
#£CONTRAST

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" && pwd  )"
cd $DIR/../..
find ./ -type f -exec sed -i 's/$background/$background/g' {} \;
find ./ -type f -exec sed -i 's/$background-ALT/$backgroundalt/g' {} \;
find ./ -type f -exec sed -i 's/$text/$text/g' {} \;
find ./ -type f -exec sed -i 's/$text-ALT/$textalt/g' {} \;
find ./ -type f -exec sed -i 's/$primary/$primary/g' {} \;
find ./ -type f -exec sed -i 's/$contrast/$contrast/g' {} \;
cd $DIR
