#!/bin/bash

background="#404552"
backgroundalt="#2F343F"
text="#FFFFFF"
textalt="#B5B5B5"
primary="#FFA726"
contrast="#6BA4E7"

terminalbackground=$(./colortrans.py "$background")
terminalbackgroundalt=$(./colortrans.py "$backgroundalt")
terminaltext=$(./colortrans.py "$text")
terminaltextalt=$(./colortrans.py "$textalt")
terminalprimary=$(./colortrans.py "$primary")
terminalcontrast=$(./colortrans.py "$contrast")

#£BACKGROUND
#£BACKGROUND-ALT
#
#£TEXT
#£TEXT-ALT
#
#£PRIMARY
#£CONTRAST

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" && pwd  )"
cd $DIR/../..
find ./ -type f -exec sed -i "s/#BACKGROUND/$background/g" {} \;
find ./ -type f -exec sed -i "s/#B-ALT/$backgroundalt/g" {} \;
find ./ -type f -exec sed -i "s/#TEXT/$text/g" {} \;
find ./ -type f -exec sed -i "s/#T-ALT/$textalt/g" {} \;
find ./ -type f -exec sed -i "s/#PRIMARY/$primary/g" {} \;
find ./ -type f -exec sed -i "s/#CONTRAST/$contrast/g" {} \;
find ./ -type f -exec sed -i "s/#TERMBACKGROUND/$terminalbackground/g" {} \;
find ./ -type f -exec sed -i "s/#TERMB-ALT/$terminalbackgroundalt/g" {} \;
find ./ -type f -exec sed -i "s/#TERMTEXT/$terminaltext/g" {} \;
find ./ -type f -exec sed -i "s/#TERMT-ALT/$terminaltextalt/g" {} \;
find ./ -type f -exec sed -i "s/#TERMPRIMARY/$terminalprimary/g" {} \;
find ./ -type f -exec sed -i "s/#TERMCONTRAST/$terminalcontrast/g" {} \;
cd $DIR
./terminal-colors
