#!/bin/sh
xrandr --output HDMI2 --off --output HDMI1 --off  --output DP1 --off --output eDP1 --scale 2x2 --panning 3840x2160+0+0 --primary --mode 1920x1080 --rotate normal --output DP2 --off
xrandr --output eDP1 --scale 1x1
xrandr --output eDP1 --scale 2x2
