#!/usr/bin/env sh

# Terminate already running bar instances
killall -q -9 polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch bar1 and bar2
polybar $1 2>/dev/null &

echo "Bars launched..."
