#!/bin/bash
artist=$(playerctl --player=google-play-music-desktop-player metadata artist 2>/dev/null)
title=$(playerctl  --player=google-play-music-desktop-player metadata title 2>/dev/null)
if [ "$artist" == "" ]; then
    artist="Nobody"
fi
if [ "$title" == "" ]; then
    title="Nothing"
fi
echo $artist '|' $title
