#!/bin/bash
pac=$(checkupdates 2>/dev/null | wc -l)

if [ "$(checkupdates 2>&1)" == "==> ERROR: Cannot fetch updates" ]
then
	pac="?"
fi

aur=$(cower -u 2>/dev/null | wc -l)

if [ "$(cower -u 2>&1)" == "error: [multi]: Couldn't resolve host name" ]
then
	aur="?"
fi

if [ "$pac" == "?" ] || [ "$aur" == "?" ]
then
    echo "%{u#5FAFD7 +u}%{F#B5B5B5}$pac | $aur%{-u}"
else
    echo "%{u#FFAF00 +u}$pac | $aur%{-u}"
fi

