#!/bin/bash

NAME=$(date +'%Y-%m-%d_%H-%M-%S')

if [ -d /home/raef/Media/Notes ]; then
	PTH=/home/raef/Media/Notes/$NAME
else
	PTH=/home/raef/Documents/Notes/$NAME
fi

vim $PTH -c 'set tw=80'

if [ -e $PTH ]; then
	cat $PTH | xclip -selection c -i
fi
